coverage:
  status:
    project:
      default:
        # basic
        target: auto #default
        threshold: 5

ignore:
  - doc/
  - internal/
  - target/
  - crates/obfs4/src/test_utils/*
  - crates/lyrebird/src/**/main.rs
