[package]
name = "obfs"
version = "0.1.0"
edition = "2021"

[lib]
name = "obfs"
crate-type = ["cdylib"]

[dependencies]
getrandom = "0.2.11"
rand = "0.8.5"
rand_core = "0.6.4"

digest = { version = "0.9", default-features = false }
siphasher = "1.0.0"
sha2 = "0.10.8"
hmac = "0.12.1"
hkdf = "0.12.3"

crypto_secretbox = "0.1.1"
subtle = "2.5.0"
curve25519-dalek = { version="4", features=["group"]}
x25519-dalek = { version = "2", features = ["static_secrets", "getrandom", "reusable_secrets"] }
group = "0.13.0"

lazy_static = "0.1.4"

hex = "0.4.3"
tracing = "0.1.40"

pin-project = "1.1.3"
futures = "0.3.29"
tokio = { version = "1.33", features = ["io-util", "rt-multi-thread", "net", "rt", "macros", "sync", "signal", "time", "fs"] }
tokio-util = { version = "0.7.10", features = ["codec"]}
bytes = "1.5.0"

[dev-dependencies]
tracing-subscriber = "0.3.18"
