services:
  client:
    image: bullseye-slim
    network: trial
    ports: 9000:9000

  client-proxy:
    image: o7-compat
    build:
      context: ../../../
      dockerfile: Dockerfile
    network: trial
    ports: 
      - 9000:9000
      - 9001:9001

  server-proxy:
    image: o7-compat
    build:
      context: ../../../
      dockerfile: Dockerfile
    network: trial
    ports: 
      - 9001:9001
      - 9002:9002

  server:
    image: bullseye-slim
    network: trial
    ports: 9002:9002

networks:
  trial
